name: Download Docker Images
on: 
  workflow_dispatch:
    inputs:
      images:
        description: 'Docker images to download (comma separated)'
        required: true
        default: 'nginx:alpine,redis:alpine'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download images
        run: |
          IFS=',' read -ra IMAGES <<< "${{ github.event.inputs.images }}"
          for img in "${IMAGES[@]}"; do
            echo "Downloading $img..."
            docker pull "$img"
            filename=$(echo "$img" | sed 's/:/-/g' | sed 's/\//-/g')
            docker save "$img" > "${filename}.tar"
            echo "Saved as ${filename}.tar"
          done
          
      - name: List created files
        run: ls -la *.tar
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: "*.tar"
