name: Download Docker Images
on: workflow_dispatch

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download images
        run: |
          docker pull nginx:alpine
          docker save nginx:alpine > nginx-alpine.tar
          ls -la *.tar
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # 更新到 v4
        with:
          name: docker-images
          path: "*.tar"
